In [6]:
# importing pandas
import pandas as pd

#fetch data and add headers
filepath = 'final_dataset_processed.csv'
column = ['complexity','token_count','loc','lloc','sloc','comments',
          'multi','blank','code_comment','h1','h2','N1','N2','vocabulary','length',
          'calculated_length','volume', 'difficulty','effort','time','bugs','defect']

df = pd.read_csv(filepath, index_col=False, usecols = column)

In [7]:
df

,complexity,token_count,loc,lloc,sloc,comments,multi,blank,code_comment,h1,...,N2,vocabulary,length,calculated_length,volume,difficulty,effort,time,bugs,defect
0,19,473,182,127,129,0,0,53,182,5,...,42,44,63,217,343,2,926,51,0,1
1,19,473,1165,710,800,67,119,181,1232,18,...,282,261,435,2000,3492,10,36473,2026,1,1
2,12,234,1392,870,1177,35,17,170,1427,14,...,531,508,811,4473,7289,7,54850,3047,2,1
3,62,1372,773,419,590,28,0,166,801,10,...,217,214,330,1598,2554,5,13587,754,0,1
4,62,1372,421,273,302,44,34,57,465,17,...,107,98,166,583,1098,11,12329,684,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42859,119,3209,1523,757,1297,19,12,193,1542,12,...,230,205,347,1508,2664,7,19053,1058,0,0
42860,119,3209,701,378,504,33,58,109,734,13,...,126,123,194,794,1346,7,10027,557,0,0
42861,124,3511,77,34,69,0,0,8,77,3,...,29,27,45,114,213,1,387,21,0,0
42862,124,3511,712,438,573,51,9,84,763,14,...,128,116,199,733,1364,8,11988,666,0,0
42863,5,319,77,34,69,0,0,8,77,3,...,29,27,45,114,213,1,387,21,0,0

In [8]:
# dropiing the duplicate rows but keeping the first row that has a duplicate below in the dataset
df.drop_duplicates(keep='first', inplace=True)
df

,complexity,token_count,loc,lloc,sloc,comments,multi,blank,code_comment,h1,...,N2,vocabulary,length,calculated_length,volume,difficulty,effort,time,bugs,defect
0,19,473,182,127,129,0,0,53,182,5,...,42,44,63,217,343,2,926,51,0,1
1,19,473,1165,710,800,67,119,181,1232,18,...,282,261,435,2000,3492,10,36473,2026,1,1
2,12,234,1392,870,1177,35,17,170,1427,14,...,531,508,811,4473,7289,7,54850,3047,2,1
3,62,1372,773,419,590,28,0,166,801,10,...,217,214,330,1598,2554,5,13587,754,0,1
4,62,1372,421,273,302,44,34,57,465,17,...,107,98,166,583,1098,11,12329,684,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42851,69,1502,402,202,227,24,74,80,426,12,...,61,64,94,339,564,7,3969,220,0,0
42852,65,2178,53,23,39,0,0,13,53,2,...,8,10,12,26,39,1,39,2,0,0
42853,65,2178,515,298,307,33,80,99,548,12,...,77,75,121,419,753,7,5527,307,0,0
42854,294,6567,72,33,56,0,4,12,72,1,...,1,2,2,0,2,0,1,0,0,0
42855,294,6567,1454,835,1044,76,110,219,1530,17,...,296,292,454,2297,3718,9,34017,1889,1,0

In [9]:
#remove rows where LOC = 0, and complexity = 0
col = ['complexity','loc']
df = df.replace(0, pd.np.nan).dropna(axis=0,how='any',subset=col).fillna(0).astype(int)
df

,complexity,token_count,loc,lloc,sloc,comments,multi,blank,code_comment,h1,...,N2,vocabulary,length,calculated_length,volume,difficulty,effort,time,bugs,defect
0,19,473,182,127,129,0,0,53,182,5,...,42,44,63,217,343,2,926,51,0,1
1,19,473,1165,710,800,67,119,181,1232,18,...,282,261,435,2000,3492,10,36473,2026,1,1
2,12,234,1392,870,1177,35,17,170,1427,14,...,531,508,811,4473,7289,7,54850,3047,2,1
3,62,1372,773,419,590,28,0,166,801,10,...,217,214,330,1598,2554,5,13587,754,0,1
4,62,1372,421,273,302,44,34,57,465,17,...,107,98,166,583,1098,11,12329,684,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42851,69,1502,402,202,227,24,74,80,426,12,...,61,64,94,339,564,7,3969,220,0,0
42852,65,2178,53,23,39,0,0,13,53,2,...,8,10,12,26,39,1,39,2,0,0
42853,65,2178,515,298,307,33,80,99,548,12,...,77,75,121,419,753,7,5527,307,0,0
42854,294,6567,72,33,56,0,4,12,72,1,...,1,2,2,0,2,0,1,0,0,0
42855,294,6567,1454,835,1044,76,110,219,1530,17,...,296,292,454,2297,3718,9,34017,1889,1,0

In [182]:
#writing release filter labelled data to CSV
df.to_csv('final_dataset_processed.csv',index=False)

In [183]:
df.dtypes

complexity           int64
token_count          int64
loc                  int64
lloc                 int64
sloc                 int64
comments             int64
multi                int64
blank                int64
code_comment         int64
h1                   int64
h2                   int64
N1                   int64
N2                   int64
vocabulary           int64
length               int64
calculated_length    int64
volume               int64
difficulty           int64
effort               int64
time                 int64
bugs                 int64
defect               int64
dtype: object

In [184]:
X = df1.iloc[:,0:-1] #features
y = df1.iloc[:,-1] #labels

In [185]:
#divide dataset into train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=None)

In [186]:
# model for Gausian NB
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
#predict model on test data
predicted = gnb.predict(X_test)

In [187]:
#get accuracy, precision, recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

accuracy_score = accuracy_score(y_test,predicted)
precision_score = precision_score(y_test,predicted)
recall_score = recall_score(y_test,predicted)
print("Accuracy:",accuracy_score)
print("Precision:",precision_score)
print("Recall:",recall_score)

Accuracy: 0.567185069984448
Precision: 0.32629727352682497
Recall: 0.37230306071249375

In [189]:
#LogisticRegression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_train)
print('Train accuracy score:',accuracy_score(y_train,y_pred))
print('Test accuracy score:', accuracy_score(y_test,logreg.predict(X_test)))

Train accuracy score: 0.6902069495526156
Test accuracy score: 0.6900466562986003

In [190]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier as RFC
rfc_b = RFC()
rfc_b.fit(X_train,y_train)
y_pred = rfc_b.predict(X_train)
print('Train accuracy score:',accuracy_score(y_train,y_pred))
print('Test accuracy score:', accuracy_score(y_test,rfc_b.predict(X_test)))

/Users/sanika/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

Train accuracy score: 0.8354284459570731
Test accuracy score: 0.6954898911353032

In [191]:
# KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_train)
print('Train accuracy score:',accuracy_score(y_train,y_pred))
print('Test accuracy score:',accuracy_score(y_test,knn.predict(X_test)))

Train accuracy score: 0.7872866004281714
Test accuracy score: 0.7255054432348367

In [188]:
#APPROACH 2 - FEATURE SELECTION (Univariate Selection)
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

X = df1.iloc[:,0:-1] #features
y = df1.iloc[:,-1] #labels

#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['features','score']  #naming the dataframe columns
print(featureScores.nlargest(10,'score'))  #print 10 best features

        features          score
1    token_count  319528.646683
0     complexity    7788.461848
6          multi    2333.753862
8   code_comment    1909.983326
2            loc    1866.380124
3           lloc    1762.407609
18        effort    1629.977633
7          blank    1617.318176
4           sloc    1348.509156
19          time    1296.774022