In [1]:
## dataset_processed_01.csv

In [2]:
# imports
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import svm

In [3]:
#fetch data and add headers
filepath = 'dataset_processed_01.csv'

df1 = pd.read_csv(filepath, index_col=False)
df1

,complexity,token_count,loc,lloc,sloc,comments,multi,blank,code_comment,h1,...,N2,vocabulary,length,calculated_length,volume,difficulty,effort,time,bugs,defect
0,19,473,182,127,129,0,0,53,182,5,...,42,44,63,217,343,2,926,51,0,1
1,19,473,1165,710,800,67,119,181,1232,18,...,282,261,435,2000,3492,10,36473,2026,1,1
2,12,234,1392,870,1177,35,17,170,1427,14,...,531,508,811,4473,7289,7,54850,3047,2,1
3,62,1372,773,419,590,28,0,166,801,10,...,217,214,330,1598,2554,5,13587,754,0,1
4,62,1372,421,273,302,44,34,57,465,17,...,107,98,166,583,1098,11,12329,684,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20047,69,1502,402,202,227,24,74,80,426,12,...,61,64,94,339,564,7,3969,220,0,0
20048,65,2178,53,23,39,0,0,13,53,2,...,8,10,12,26,39,1,39,2,0,0
20049,65,2178,515,298,307,33,80,99,548,12,...,77,75,121,419,753,7,5527,307,0,0
20050,294,6567,72,33,56,0,4,12,72,1,...,1,2,2,0,2,0,1,0,0,0
20051,294,6567,1454,835,1044,76,110,219,1530,17,...,296,292,454,2297,3718,9,34017,1889,1,0

In [4]:
df1.dtypes

complexity           int64
token_count          int64
loc                  int64
lloc                 int64
sloc                 int64
comments             int64
multi                int64
blank                int64
code_comment         int64
h1                   int64
h2                   int64
N1                   int64
N2                   int64
vocabulary           int64
length               int64
calculated_length    int64
volume               int64
difficulty           int64
effort               int64
time                 int64
bugs                 int64
defect               int64
dtype: object

In [5]:
X = df1.iloc[:,0:-1] #features
y = df1.iloc[:,-1] #labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=None) 

#Create a svm Classifier
clf = svm.SVC(gamma='auto') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))
# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.4429853723404255
Precision: 0.3445732349841939
Recall: 0.23687069902209346

In [6]:
## dataset_processed_02.csv

In [24]:
#fetch data and add headers
filepath = 'dataset_processed_02.csv'

df2 = pd.read_csv(filepath, index_col=False)
X = df1.iloc[:,0:-1] #features
y = df1.iloc[:,-1] #labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.09, random_state=None) 

#Create a svm Classifier
clf = svm.SVC(gamma='auto') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))
# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.421606648199446
Precision: 0.33560477001703576
Recall: 0.23149236192714454

In [11]:
## dataset_processed_03.csv

In [12]:
#fetch data and add headers
filepath = 'dataset_processed_03.csv'

df3 = pd.read_csv(filepath, index_col=False)
X = df3.iloc[:,0:-1] #features
y = df3.iloc[:,-1] #labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=None) 

#Create a svm Classifier
clf = svm.SVC(gamma='auto') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))
# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.7146458678011502
Precision: 0.9320652173913043
Recall: 0.08705583756345178

In [13]:
df3

,complexity,token_count,loc,lloc,sloc,comments,multi,blank,code_comment,h1,...,time,bugs,change_type,added,removed,introspection,object_changes,code_generation,library_loading,defect
0,19,473,182,127,129,0,0,53,182,5,...,51,0,0,80,0,170,62,16,132,1
1,19,473,1165,710,800,67,119,181,1232,18,...,2026,1,0,80,0,180,62,17,133,1
2,12,234,1392,870,1177,35,17,170,1427,14,...,3047,2,0,40,0,180,65,18,134,1
3,62,1372,773,419,590,28,0,166,801,10,...,754,0,0,282,0,180,65,19,135,1
4,62,1372,421,273,302,44,34,57,465,17,...,684,0,0,282,0,180,65,20,136,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42302,119,3209,1523,757,1297,19,12,193,1542,12,...,1058,0,2,1,1,95700,37606,7739,50797,0
42303,119,3209,701,378,504,33,58,109,734,13,...,557,0,2,1,1,95700,37607,7740,50798,0
42304,124,3511,77,34,69,0,0,8,77,3,...,21,0,2,20,10,95700,37607,7740,50799,0
42305,124,3511,712,438,573,51,9,84,763,14,...,666,0,2,20,10,95710,37608,7740,50800,0
42306,5,319,77,34,69,0,0,8,77,3,...,21,0,2,25,0,95710,37608,7740,50801,0

In [14]:
## promise_CM1.csv

In [15]:
#fetch data and add headers
filepath = 'promise_CM1.csv'

df4 = pd.read_csv(filepath, header = None)
X = df4.iloc[:,0:-1] #features
y = df4.iloc[:,-1] #labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=None) 

#Create a svm Classifier
clf = svm.SVC(gamma='auto') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))
# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.8933333333333333
Precision: 1.0
Recall: 0.058823529411764705

In [16]:
df4

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,1.1,1.4,1.4,1.4,1.3,1.30,1.30,1.30,1.30,1.30,...,2,2,2,2,1.2,1.2,1.2,1.2,1.4,False
1,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.00,...,1,1,1,1,1.0,1.0,1.0,1.0,1.0,True
2,24.0,5.0,1.0,3.0,63.0,309.13,0.11,9.50,32.54,2936.77,...,1,0,6,0,15.0,15.0,44.0,19.0,9.0,False
3,20.0,4.0,4.0,2.0,47.0,215.49,0.06,16.00,13.47,3447.89,...,0,0,3,0,16.0,8.0,31.0,16.0,7.0,False
4,24.0,6.0,6.0,2.0,72.0,346.13,0.06,17.33,19.97,5999.58,...,0,0,3,0,16.0,12.0,46.0,26.0,11.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,47.0,3.0,1.0,3.0,256.0,1563.78,0.04,28.00,55.85,43785.90,...,2,13,2,0,23.0,46.0,144.0,112.0,5.0,True
494,24.0,4.0,3.0,3.0,107.0,587.63,0.05,19.13,30.72,11241.58,...,1,7,4,0,22.0,23.0,67.0,40.0,7.0,True
495,82.0,11.0,3.0,10.0,475.0,3155.83,0.02,44.71,70.59,141084.24,...,9,59,35,0,32.0,68.0,285.0,190.0,21.0,True
496,10.0,2.0,1.0,1.0,32.0,150.41,0.15,6.50,23.14,977.69,...,1,12,4,0,13.0,13.0,19.0,13.0,3.0,True
497,28.0,6.0,5.0,5.0,104.0,564.33,0.06,16.09,35.08,9078.38,...,2,7,0,0,20.0,23.0,67.0,37.0,11.0,True

In [17]:
filepath = 'promise_CM1.csv'

df4 = pd.read_csv(filepath, index_col=False)
df4.dtypes

1.1        int64
1.4        int64
1.4.1      int64
1.4.2      int64
1.3        int64
1.3.1    float64
1.3.2    float64
1.3.3    float64
1.3.4    float64
1.3.5    float64
1.3.6    float64
1.3.7    float64
2          int64
2.1        int64
2.2        int64
2.3        int64
1.2        int64
1.2.1      int64
1.2.2      int64
1.2.3      int64
1.4.3      int64
false       bool
dtype: object

In [18]:
## promise_KC3.csv

In [35]:
#fetch data and add headers
filepath = 'promise_KC3.csv'

from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
# >>> scores = cross_val_score(clf, X, y, cv=5)

df5 = pd.read_csv(filepath,header = None)
X = df5.iloc[:,0:-1] #features
y = df5.iloc[:,-1] #labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,shuffle = True) 


#Create a svm Classifier
clf = svm.SVC(kernel='rbf',gamma='auto') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))
# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

confusion_matrix(y_test,y_pred)

Accuracy: 0.9130434782608695
Precision: 0.0
Recall: 0.0

/Users/sanika/anaconda3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

array([[126,   0],
       [ 12,   0]])

In [31]:
df5

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,0,1,1,0,0,0,1,0.33,0,0.00,...,3,0.25,3,6,3,6,4,0.00,3,False
1,1,5,4,0,0,8,3,0.27,4,2.00,...,12,0.23,21,36,12,13,13,0.00,11,False
2,0,1,0,0,0,0,1,0.33,0,0.00,...,2,0.25,2,5,1,5,4,0.00,3,False
3,0,1,0,0,0,0,1,0.33,0,0.00,...,2,0.25,2,5,2,5,4,0.00,3,False
4,5,18,18,0,2,20,10,0.17,10,2.00,...,54,0.15,92,177,48,25,66,3.33,58,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,1,8,5,0,0,8,5,0.21,4,2.00,...,19,0.19,36,68,23,16,26,0.00,24,False
454,2,1,7,0,1,0,1,0.09,0,0.00,...,10,0.06,36,51,24,11,16,8.33,11,False
455,7,12,16,1,0,16,7,0.19,8,2.00,...,42,0.16,77,140,39,19,44,2.78,36,False
456,1,1,3,0,0,0,1,0.25,0,0.00,...,5,0.17,11,17,9,7,6,0.00,4,False
457,22,43,20,3,11,38,26,0.20,18,2.11,...,108,0.16,255,411,91,30,166,9.86,131,False